group: latent_hendrycks_math_cot
task:
  - latent_hendrycks_math_cot_algebra
  - latent_hendrycks_math_cot_counting_and_prob
  - latent_hendrycks_math_cot_geometry
  - latent_hendrycks_math_cot_intermediate_algebra
  - latent_hendrycks_math_cot_num_theory
  - latent_hendrycks_math_cot_prealgebra
  - latent_hendrycks_math_cot_precalc
aggregate_metric_list:
  - metric: exact_match
    aggregation: mean
    weight_by_size: true
metadata:
  version: 1.0